# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      # pip3
      - python3-pip

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5-pic-hid-sections-lto INSTALL=--strip

    # }

    # OSX {

    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-11-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-10-1-arm64-dep-9-0-device-libcxx-hid-sections-lto INSTALL=--install

    - os: osx
      osx_image: xcode8.1
      env: CONFIG=Release TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install

    - os: osx
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections INSTALL=--strip

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings

install:
  - source bin/hunter_env.sh
  
script:
  - travis_wait 200 bin/drishti_build.sh "${TOOLCHAIN}" "${CONFIG}" "${INSTALL}"

before_deploy:
    - gem install mime-types -v 2.6.2 # workaround for https://github.com/travis-ci/travis-ci/issues/5145
    - export FILE_TO_UPLOAD=$(ls _archives/drishti-*.tar.gz)

deploy:
  provider: releases
  api_key:
    - secure: "T6lcJJydAxf4lc+jLmaBK3wp3xxNnI5pYb5+sSnJ5t4fBuNMjRP48+YAd9cB4bi3ndO+n4yWBwRWEZXdRA5LSjszgbs7gv7WSBaTXyYQnldT2JRU3Qz/mPVLQxalectfIltAc54F6ioXTAy4uflpzMeMYuvQNMDD+M0ZOucoHaolNYYU3DIRbb7npzKjYPigZui3ynfg5yeeTdCYuiFoezFoRGTj7WxUGpn8vQn8kQmDg6UwL27MagfQdnLEaozEC/NbLK/Gl+PC4QTKUfb32JDGP/QaFfzxQ9qsISvAd23pQot6VIBy+OcRMG/qdw4JkO82iRlCWEjCFsybsAFQv3yhFBvxoeGGuxVshs6tXcVDokRRvceN1oeApAFHATYsv0xwdATnoul9UxaPukFmvFzFVezgUgcbrHoUXiZbK1lcvMuSUyLUKFP8i1CR8VAmmPXDc09jn7mMuX3+UIOmk2BgjhtGoX3oUN4LV29/P57NZ7loyHfZUrNokHg5am9lPsZshC64cB/iLP0jh0giofr9iPVXFxk00qa6JHgYOdpLduMkEhwASPijV7JUV2OikvUODYGMVeVVhdbHhW/UbvS0Rc/I64scHGWDJSh81zUszdPNBuG6SidYlC7UXnOw6XIql8sNeV1gsaysMKdthe9kbKYlFEXpL45pvZwgoK0="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^pr\..*/
